In [2]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_5158bfd5065b40c4b6cf7e02a60cf879 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='Rob46tTNo97O_Wdw9cPUe7whW_akOBfAuD9qWugyZBTB',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

body = client_5158bfd5065b40c4b6cf7e02a60cf879.get_object(Bucket='ibmsmartlender-donotdelete-pr-fn1gcvrcmxp1mg',Key='test.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

test = pd.read_csv(body)
test.head()


Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        1           0          0              0         9.114160   
1       1        1           0          0              0         8.368693   
2       1        1           2          0              0         8.334952   
3       0        0           0          0              0         7.972466   
4       1        0           0          0              0         7.907652   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0    5.429346             360.0               1   
1                0.0    4.867534             360.0               1   
2             1447.0    5.062595             360.0               1   
3                0.0    4.262680             360.0               1   
4                0.0    4.248495             360.0               1   

   Property_Area  Loan_Status  
0              1            1  
1              1            1  
2              0            1  
3              0            1  
4              1            1

In [3]:

body = client_5158bfd5065b40c4b6cf7e02a60cf879.get_object(Bucket='ibmsmartlender-donotdelete-pr-fn1gcvrcmxp1mg',Key='train.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

train= pd.read_csv(body)
train.head()


Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        1           0          0              0         8.699515   
1       1        1           0          0              0         7.992269   
2       1        1           2          0              0         8.740337   
3       1        1           0          0              0         7.641564   
4       1        0           0          0              0         8.334712   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0             2250.0    5.579730             360.0               1   
1             2900.0    4.875197             360.0               1   
2             1695.0    5.347108             360.0               1   
3             3150.0    4.852030             360.0               1   
4                0.0    4.584967             360.0               0   

   Property_Area  Loan_Status  
0              1            0  
1              1            1  
2              1            1  
3              1            1  
4              1            0

In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MaxAbsScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score
import pickle

In [5]:
scaler = MaxAbsScaler()

In [6]:
train.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        1           0          0              0         8.699515   
1       1        1           0          0              0         7.992269   
2       1        1           2          0              0         8.740337   
3       1        1           0          0              0         7.641564   
4       1        0           0          0              0         8.334712   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0             2250.0    5.579730             360.0               1   
1             2900.0    4.875197             360.0               1   
2             1695.0    5.347108             360.0               1   
3             3150.0    4.852030             360.0               1   
4                0.0    4.584967             360.0               0   

   Property_Area  Loan_Status  
0              1            0  
1              1            1  
2              1            1  
3              1            1  
4              1            0

In [7]:
train_y = train.iloc[:,-1]

In [8]:
train_x = train.drop('Loan_Status',axis=1)

In [9]:
test_y = test.iloc[:,-1]

In [10]:
test_x = test.drop('Loan_Status',axis=1)

In [11]:
x = pd.concat([train_x,test_x],axis=0)
y = pd.concat([train_y,test_y],axis=0)

In [12]:
train_x = scaler.fit_transform(train_x)

In [13]:
test_x = scaler.transform(test_x)

In [14]:
def decisionTree(train_x,test_x,train_y,test_y):
    dt = DecisionTreeClassifier()
    dt.fit(train_x,train_y)
    y_pred = dt.predict(test_x)
    print("**** Decision Tree Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

In [15]:
def randomForest(train_x,test_x,train_y,test_y):
    rf = RandomForestClassifier()
    rf.fit(train_x,train_y)
    y_pred = rf.predict(test_x)
    print("**** Random Forest Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

In [16]:
def knn(train_x,test_x,train_y,test_y):
    knn = KNeighborsClassifier()
    knn.fit(train_x,train_y)
    y_pred = knn.predict(test_x)
    print("**** KNeighbour Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

In [17]:
def xgboost(train_x,test_x,train_y,test_y):
    xg = GradientBoostingClassifier()
    xg.fit(train_x,train_y)
    y_pred = xg.predict(test_x)
    print("**** Gradient Boosting Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

In [18]:
decisionTree(train_x,test_x,train_y,test_y)

**** Decision Tree Classifier ****
Confusion Matrix
[[24 19]
 [16 64]]
Classification Report
              precision    recall  f1-score   support

           0       0.60      0.56      0.58        43
           1       0.77      0.80      0.79        80

    accuracy                           0.72       123
   macro avg       0.69      0.68      0.68       123
weighted avg       0.71      0.72      0.71       123



In [19]:
randomForest(train_x,test_x,train_y,test_y)

**** Random Forest Classifier ****
Confusion Matrix
[[18 25]
 [ 2 78]]
Classification Report
              precision    recall  f1-score   support

           0       0.90      0.42      0.57        43
           1       0.76      0.97      0.85        80

    accuracy                           0.78       123
   macro avg       0.83      0.70      0.71       123
weighted avg       0.81      0.78      0.75       123



In [20]:
knn(train_x,test_x,train_y,test_y)

**** KNeighbour Classifier ****
Confusion Matrix
[[18 25]
 [ 7 73]]
Classification Report
              precision    recall  f1-score   support

           0       0.72      0.42      0.53        43
           1       0.74      0.91      0.82        80

    accuracy                           0.74       123
   macro avg       0.73      0.67      0.67       123
weighted avg       0.74      0.74      0.72       123



In [21]:
xgboost(train_x,test_x,train_y,test_y)

**** Gradient Boosting Classifier ****
Confusion Matrix
[[19 24]
 [ 8 72]]
Classification Report
              precision    recall  f1-score   support

           0       0.70      0.44      0.54        43
           1       0.75      0.90      0.82        80

    accuracy                           0.74       123
   macro avg       0.73      0.67      0.68       123
weighted avg       0.73      0.74      0.72       123



In [22]:
rf = RandomForestClassifier()
rf.fit(train_x,train_y)
ypred = rf.predict(test_x)


In [23]:
f1_score(ypred,test_y,average='weighted')

0.7977251407129455

In [24]:
cv = cross_val_score(rf,x,y,cv=5)

In [25]:
np.mean(cv)

0.8029321604691455

In [27]:
!pip install -U ibm-watson-machine-learning

     |████████████████████████████████| 1.8 MB 11.0 MB/s eta 0:00:01████████████████████         | 1.3 MB 11.0 MB/s eta 0:00:01
  Attempting uninstall: ibm-watson-machine-learning
    Found existing installation: ibm-watson-machine-learning 1.0.255
    Uninstalling ibm-watson-machine-learning-1.0.255:
      Successfully uninstalled ibm-watson-machine-learning-1.0.255


In [28]:
from ibm_watson_machine_learning import APIClient
import json

In [30]:
###  Authenticate and set space

In [31]:
wml_credentials = {
    "apikey" : "hmIOFhnjuvRGrJaKtFnyvNKEQTINuL4eRrcnbp6K7c8R",
    "url" : "https://us-south.ml.cloud.ibm.com"
}

In [32]:
wml_client = APIClient(wml_credentials)

In [33]:
wml_client.spaces.list()

Note: 'limit' is not provided. Only first 50 records will be displayed if the number of records exceed 50
------------------------------------  ------------  ------------------------
ID                                    NAME          CREATED
877f81dd-5be6-4bf6-a0f9-54dc995e4548  Smart-Lender  2022-10-25T15:59:31.208Z
------------------------------------  ------------  ------------------------


In [34]:
SPACE_ID= "877f81dd-5be6-4bf6-a0f9-54dc995e4548"

In [35]:
wml_client.set.default_space(SPACE_ID)

'SUCCESS'

In [36]:
wml_client.software_specifications.list(100)

-------------------------------  ------------------------------------  ----
NAME                             ASSET_ID                              TYPE
default_py3.6                    0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
kernel-spark3.2-scala2.12        020d69ce-7ac1-5e68-ac1a-31189867356a  base
pytorch-onnx_1.3-py3.7-edt       069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6          09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12       09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
pytorch-onnx_rt22.1-py3.9        0b848dd4-e681-5599-be41-b5f6fccc6471  base
ai-function_0.1-py3.6            0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                       0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod     1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6                10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl        111e41b3-de2d-5422-a4d6-bf776828c4b7  base
runtime-22.1

###  Save and deploy

In [39]:
import sklearn
sklearn.__version__

'1.0.2'

In [42]:
MODEL_NAME = 'Model_building_SL'
DEPLOYMENT_NAME = 'Smart-Lender'
DEMO_MODEL = rf

In [43]:
software_spec_uid = wml_client.software_specifications.get_id_by_name('runtime-22.1-py3.9')

In [44]:
model_props = {
    wml_client.repository.ModelMetaNames.NAME: MODEL_NAME, 
    wml_client.repository.ModelMetaNames.TYPE: 'scikit-learn_1.0', 
    wml_client.repository.ModelMetaNames.SOFTWARE_SPEC_UID: software_spec_uid 
}

In [46]:
model_details = wml_client.repository.store_model(
    model=DEMO_MODEL, 
    meta_props=model_props, 
    training_data=train_x, 
    training_target=train_y
)

In [47]:
model_details

{'entity': {'hybrid_pipeline_software_specs': [],
  'label_column': 'Loan_Status',
  'schemas': {'input': [{'fields': [{'name': 'f0', 'type': 'float'},
      {'name': 'f1', 'type': 'float'},
      {'name': 'f2', 'type': 'float'},
      {'name': 'f3', 'type': 'float'},
      {'name': 'f4', 'type': 'float'},
      {'name': 'f5', 'type': 'float'},
      {'name': 'f6', 'type': 'float'},
      {'name': 'f7', 'type': 'float'},
      {'name': 'f8', 'type': 'float'},
      {'name': 'f9', 'type': 'float'},
      {'name': 'f10', 'type': 'float'}],
     'id': '1',
     'type': 'struct'}],
   'output': []},
  'software_spec': {'id': '12b83a17-24d8-5082-900f-0ab31fbfd3cb',
   'name': 'runtime-22.1-py3.9'},
  'type': 'scikit-learn_1.0'},
 'metadata': {'created_at': '2022-10-26T05:52:23.247Z',
  'id': '67afa6fa-bd13-400f-bc54-bbaaf4cfca37',
  'modified_at': '2022-10-26T05:52:26.882Z',
  'name': 'Model_building_SL',
  'owner': 'IBMid-664003ZV1K',
  'resource_key': 'ba88dbbe-4678-4f41-b097-ba6ee46736f9

In [48]:
model_id = wml_client.repository.get_model_id(model_details)
model_id

'67afa6fa-bd13-400f-bc54-bbaaf4cfca37'

In [49]:
deployment_props = {
    wml_client.deployments.ConfigurationMetaNames.NAME:DEPLOYMENT_NAME, 
    wml_client.deployments.ConfigurationMetaNames.ONLINE: {}
}

In [50]:
deployment = wml_client.deployments.create(
    artifact_uid=model_id, 
    meta_props=deployment_props 
)



#######################################################################################

Synchronous deployment creation for uid: '67afa6fa-bd13-400f-bc54-bbaaf4cfca37' started

#######################################################################################


initializing
Note: online_url is deprecated and will be removed in a future release. Use serving_urls instead.

ready


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='5108313c-f101-4c06-8f87-151aa0d1c3ff'
------------------------------------------------------------------------------------------------


